import type { Metadata } from 'next';
import { site } from '@/content/site';

export type OgImageSlug = 'home' | 'studio' | 'ventures' | 'thesis' | 'insights' | 'about' | 'contact';

/**
 * Share images live in public/og/ and are generated by `npm run og`.
 * WhatsApp, Discord and others cache previews by image URL, so bump
 * OG_VERSION whenever the images change to make them fetch the new ones.
 */
const OG_VERSION = 2;

export function ogImage(slug: OgImageSlug, alt: string) {
  return { url: `/og/${slug}.jpg?v=${OG_VERSION}`, width: 1200, height: 630, alt, type: 'image/jpeg' };
}

export const homeOgImage = ogImage(
  'home',
  'QuantumX Ventures: Quantum, put to work. A dilution refrigerator of a quantum computer beside the headline.',
);

/**
 * Per-page metadata. Next.js replaces (not merges) the root openGraph and
 * twitter objects when a page defines its own, so every field a page needs,
 * including the share image, is set here explicitly.
 */
export function pageMetadata({
  title,
  socialTitle,
  description,
  path,
  image,
}: {
  /** Page title. The root template appends " | QuantumX Ventures". Keep it under ~40 characters. */
  title: string;
  /** Optional shorter, punchier title for link previews. Defaults to the full page title. */
  socialTitle?: string;
  /** 120 to 160 characters. Shown in search results and link previews. */
  description: string;
  path: string;
  image: { slug: OgImageSlug; alt: string };
}): Metadata {
  const fullTitle = `${(socialTitle ?? title).replace(/\.$/, '')} | ${site.name}`;
  const images = [ogImage(image.slug, image.alt)];
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      locale: 'en_US',
      siteName: site.name,
      url: path,
      title: fullTitle,
      description,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      site: site.twitterHandle,
      title: fullTitle,
      description,
      images,
    },
  };
}
